In [24]:
import numpy as np

print("Listas")
a = [[1,2,3],(4,5)]
print(a)
print(a*3)
a = a + [7,8]
print(a)
print(len(a))
a = a*3
a.append(5)
print(a)
print(len(a))

print("\n\nNumpy array")
v = np.linspace(0,10,5)
print(v)
print(v*2)
print(np.concatenate((   ([1,2,3],[1,2,3])  ,  ([4,5,6],[4,5,6])   )  ,0))

print("\n\nDicionario ")
b = {"Chave1":1,2:"Valor2"}
print(b['Chave1'])
print(b[2])
print(np.array(list(b.items())))
print(np.array(list(b.items())[0]))
print(np.array(list(b.items())[0][0]))


print("\n\nNumpy Record")
c = np.array([ (1,(2.0,3.0),'hey') , (2,(3.5,4.0),'n')] ,
                dtype=[ ('x',np.int32), ('y',np.float64,2), ('z',np.str,4)])

print(c[0][1][0])
print(c[0][1][1])
print(c['x'])


Listas
[[1, 2, 3], (4, 5)]
[[1, 2, 3], (4, 5), [1, 2, 3], (4, 5), [1, 2, 3], (4, 5)]
[[1, 2, 3], (4, 5), 7, 8]
4
[[1, 2, 3], (4, 5), 7, 8, [1, 2, 3], (4, 5), 7, 8, [1, 2, 3], (4, 5), 7, 8, 5]
13


Numpy array
[  0.    2.5   5.    7.5  10. ]
[  0.   5.  10.  15.  20.]
[[1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]]


Dicionario 
1
Valor2
[['2' 'Valor2']
 ['Chave1' '1']]
['2' 'Valor2']
2


Numpy Record
2.0
3.0
[1 2]
